### ISSUE TITLE
Investigate Makefile and determine compilation issue

### ISSUE THREAD

**Issue by Anthony-T-N** [inft3063-assignment-1-wed-atb/INFT2063_Assignment_1#6]
The Makefile currently cannot compile due to an unknown issue. Requesting any assignee to investigate the source of the issue and to resolve the problem at hand.

**Comment by bjcham69** [comment]
makefile compiles the java program, I tried to compile and run the program with the command line, 
>javac CashRegister.java 
>java CashRegister
It compiled and ran properly so I think the error might be in the command that compiles the java file in the makefile.

**Comment by tinothy** [comment]
I think i know the problem.  On line 9 there is a spelling error. Should be Transaction.class. It was missing an 's' in class
