### ISSUE TITLE
Remove cash register balance

### ISSUE THREAD

**Issue by tinothy** [inft3063-assignment-1-wed-atb/INFT2063_Assignment_1#9]
Remove the display of the cash register balance after each transaction and only display at the end when the user quits.

**Comment by Anthony-T-N** [comment]
Requesting clarification regarding to resolving this issue:
Would you like me to add the display of the cash register balance when the user enters no (n) when prompted to respond to "Would you like to proceed with the transaction? (y/n)" ?

**Comment by tinothy** [comment]
yeah that sounds great, go for it Anthony

**Comment by Anthony-T-N** [comment]
Thanks, I'll get to it.

**Comment by Anthony-T-N** [comment]
Resolved the issue. The program now displays the cash register balance at the end when the user chooses to quit.
